apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  generation: 1
  labels:
    app: datamodel
  name: datamodel-create-8e34c91-1
  namespace: default
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 2
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
     spec:
      containers:
      - name: sleep
        image: busybox
        command: ["/bin/sh","-c", "sleep 10000 && exit 1"]
        imagePullPolicy: Always
        name: datamodel-create
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
