apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  generation: 1
  labels:
    app: datamodel
  name: datamodel-create-8e34c91-1
  namespace: default
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 2
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      labels:
        app: datamodel
        controller-uid: cc13c68b-c885-4666-a2c1-e4210184c3e8
        job-name: datamodel-create-8e34c91-1
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
        imagePullPolicy: Always
        name: datamodel-create
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
